services:
  mysql:
    image: mysql:8.0
    container_name: mysql_menu_generator
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mysql_menu_generator_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - ./menu_generator_data:/var/lib/mysql
